# Generated by Django 4.0.3 on 2024-11-20 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('title', models.CharField(default='Lesson X', max_length=200)),
                ('description', models.TextField(default='Enter description')),
                ('vimeo_id', models.CharField(default='000000000', max_length=50)),
                ('length', models.IntegerField(default=5)),
                ('thumbnail_id', models.IntegerField(default=100)),
                ('lesson_file', models.CharField(default='lesson_file', max_length=60)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.lesson')),
                ('question', models.CharField(default='Question', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_info', models.JSONField(default=main_app.models.Profile.default_progress_info)),
                ('community_member', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('file', models.CharField(max_length=30)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main_app.quiz')),
            ],
            options={
                'ordering': ['answer_id'],
            },
        ),
    ]
