# Generated by Django 5.1.3 on 2024-11-22 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_quiz_question_quizquestion_delete_quizanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='lesson',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main_app.lesson'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
