# Generated by Django 5.1.3 on 2024-11-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_quizquestion_quiz_quizquestion_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='audio_file',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
