# Generated by Django 5.1.3 on 2024-11-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_quizquestion_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='bonus_lesson',
            field=models.BooleanField(default=False),
        ),
    ]
